### ISSUE TITLE
Suggestion: FTPiiU (Everywhere?) Plugin

### ISSUE THREAD

**Issue by ghost** [wiiu-env/WiiUPluginSystem#16]
The idea behind this comes from the WebMan plugin for PS3. It allows you to enable a FTP server that you can access at any point, even while playing games.
It might not be useful for the majority of users though.

**Comment by downloadpizza** [comment]
Actually it might be, you could modify ram while a game is running,

**Comment by ghost** [comment]
I think you're thinking of TCPGecko. TCPGecko is for modifying values in games and commonly used for cheats and stuff.
FTPiiU (Everywhere) is for copying files to/from the system (Internal Memory, USB, SD Card, etc).

**Comment by mariomadproductions** [comment]
You could use it for testing game mods, e.g.
* edit level on pc
* send to wii u's SDCaffine folder
* play level
* exit level
* repeat

edit: actually, at least in some circumstances, it might be better for sdcaffine to be given network functionality (like the old non-sd "caffine")

**Comment by Maschell** [comment]
https://www.bountysource.com/issues/56218249-suggestion-ftpiiu-everywhere-plugin

**Comment by jack4455667788** [comment]
You can almost already do this using the DiiBugger plugin.  I converted a bunch of the codes for botw, but it was a pain.

Of course, unless you program something to continue to overwrite the address, persistent codes (and other programmatic ram editing code logic) will not work.
