### ISSUE TITLE
Testing the Memory Mapping.

### ISSUE THREAD

**Issue by Maschell** [wiiu-env/WiiUPluginSystem#17]
Commit https://github.com/Maschell/WiiUPluginSystem/commit/a839430ea0c20ae08821b8b9b226d77d0d117e30 added inital support for mapping some extra memory.
This memory is currently not used as it's still unclear if it's really unused.
To check this, I need some people to run some tests on their console. At the moment I have only done it on mine ( EUR 5.5.2).
What the memory mapping testing is doing:
- Setting up the segment registers and page table to map memory to (hopefully) unused places
- Write specific values to the _physical_ addresses of the memory
- Then reading it the values from the _effective__ addresses of the memory and comparing them
- Check if memory was overriden (=> was not unused memory..)
- Loading it with any plugins is NOT required.

What the tester should do:
- Download the nightly: https://github.com/Maschell/WiiUPluginSystem/releases/tag/WiiUPluginLoader-alpha-nightly-b4a07cf
- **Please add the information of which nightly was used** (or post the full log)
- Run the plugin loader elf via the homebrew launcher
- Start the [UDPDebugReader](https://github.com/Maschell/WiiUPluginSystem/tree/master/tools/udp_debug_reader) 
- Press **MINUS** on the gamepad to map the memory and return to the system menu. This takes a moment, writing to the physical memory addresses is slow. You can see the progress in the log

Once you are in the system menu, check the log for something like this
```
[     memory_mapping.cpp]      readTestValuesFromMemory@L0213: Testing reading the written values.
[     memory_mapping.cpp]      readTestValuesFromMemory@L0236: Flushing 00800000 (8192 kB) at 80000000 to map memory.
[     memory_mapping.cpp]      readTestValuesFromMemory@L0239: Testing memory region 1. 0x80000000 - 0x80800000. Size 0x00800000 (8192 KBytes).
[     memory_mapping.cpp]      readTestValuesFromMemory@L0266: + Good  between 0x80000000 and 0x80800000 size: 8192 kB
[     memory_mapping.cpp]      readTestValuesFromMemory@L0271: Test 1 was successful!
[     memory_mapping.cpp]      readTestValuesFromMemory@L0236: Flushing 01000000 (16384 kB) at 80800000 to map memory.
[     memory_mapping.cpp]      readTestValuesFromMemory@L0239: Testing memory region 2. 0x80800000 - 0x81800000. Size 0x01000000 (16384 KBytes).
[     memory_mapping.cpp]      readTestValuesFromMemory@L0266: + Good  between 0x80800000 and 0x81800000 size: 16384 kB
[     memory_mapping.cpp]      readTestValuesFromMemory@L0271: Test 2 was successful!
[     memory_mapping.cpp]      readTestValuesFromMemory@L0236: Flushing 02B40000 (44288 kB) at 88000000 to map memory.
[     memory_mapping.cpp]      readTestValuesFromMemory@L0239: Testing memory region 3. 0x88000000 - 0x8AB40000. Size 0x02B40000 (44288 KBytes).
[     memory_mapping.cpp]      readTestValuesFromMemory@L0266: + Good  between 0x88000000 and 0x8AB40000 size: 44288 kB
[     memory_mapping.cpp]      readTestValuesFromMemory@L0271: Test 3 was successful!
[     memory_mapping.cpp]      readTestValuesFromMemory@L0275: All tests done.
````

This gets logged whenever the application was switched. However, you can trigger it manually by pressing **L,R and PLUS** on the Gamepad. The goal is now trying override the mapped memory so the test is failing. In best case our mapped memory is really unused, and overriding  is impossible. Otherwise we have to exclude the overridden memory.

So how to break this?

- Try to load as many games as possible. Maybe some game already used the memory region we mapped our to.
- Attach some peripheral like USB Controllers, keyboard, 
- Open overlay apps. Browser, Friendlist, Miiverse, EShop, Browser, Notification, Downloader Manager, Manual. Combine this. While ingame open notifcation and jump to the browser. Stuff like that.
- Try to use the gamepad camera (in game, miimaker not available) or NFC sensor.
- Get creative. I want this to be as stable a possible. So even if some parts of the memory are only used in really rare and strange situations - I won't take it.
- Load different virtual console games (I only tested nes and snes so far)

Keep a copy of the UDPReader log. You can press "f" to save the log to the files. If you found something interesting, copy/paste the log in here.

**If you see any crash, please send me the full log (+ some details where it crashed).**
It would be also awesome if you could re-run the step to trigger the step, but load the plugin loader normally this time (with **Plus**). This still logs some memory stuff, but doesn't map new memory (and hopefully don't crash). Both logs would be very helpful.

If you have any questions, feel free to ask!

FAQ:
**Will the memory mapping always take sooooo long?**
No. Only writing 65MB to the physical memory addresses is slow. This is not required, only for testing.
**Why do we need to map extra memory?**
More plugins at the same time. Memory is always good. This is also a huge step into getting plugins working together with homebrew applications.

**Comment by piratesephiroth** [comment]
I'm using a North American 8GB Wii U on v5.5.2

I saw errors only on region 3. It happens after I go to Notifications and then click an outdated eShop link, like Kirby 25th Anniversary (get an error 111-1006, cannot display the page).

I guess it's caused by any error while loading the eshop.

Testing memory region 3. 0x88000000 - 0x8AB40000. Size 0x02B40000 (44288 KBytes).
+ Good  between 0x88000000 and 0x88856800 size: 8538 kB
- Error between 0x88856800 and 0x88860340 size: 38 kB
+ Good  between 0x88860340 and 0x88860800 size: 1 kB
- Error between 0x88860800 and 0x88880000 size: 126 kB
+ Good  between 0x88880000 and 0x8AB40000 size: 35584 kB

**Comment by FunThomas76** [comment]
EU WiiU 32GB on 5.5.1:

Testing reading the written values.
Flushing 00800000 (8192 kB) at 80000000 to map memory.
Testing memory region 1. 0x80000000 - 0x80800000. Size 0x00800000 (8192 KBytes).
+ Good  between 0x80000000 and 0x80800000 size: 8192 kB
Test 1 was successful!
Flushing 01000000 (16384 kB) at 80800000 to map memory.
Testing memory region 2. 0x80800000 - 0x81800000. Size 0x01000000 (16384 KBytes).
+ Good  between 0x80800000 and 0x81800000 size: 16384 kB
Test 2 was successful!
Flushing 02B40000 (44288 kB) at 88000000 to map memory.
Testing memory region 3. 0x88000000 - 0x8AB40000. Size 0x02B40000 (44288 KBytes).
+ Good  between 0x88000000 and 0x8AB40000 size: 44288 kB
Test 3 was successful!
All tests done.
Testing reading the written values.
Flushing 00800000 (8192 kB) at 80000000 to map memory.
Testing memory region 1. 0x80000000 - 0x80800000. Size 0x00800000 (8192 KBytes).
+ Good  between 0x80000000 and 0x80800000 size: 8192 kB
Test 1 was successful!
Flushing 01000000 (16384 kB) at 80800000 to map memory.
Testing memory region 2. 0x80800000 - 0x81800000. Size 0x01000000 (16384 KBytes).
+ Good  between 0x80800000 and 0x81800000 size: 16384 kB
Test 2 was successful!
Flushing 02B40000 (44288 kB) at 88000000 to map memory.
Testing memory region 3. 0x88000000 - 0x8AB40000. Size 0x02B40000 (44288 KBytes).
+ Good  between 0x88000000 and 0x8AB40000 size: 44288 kB
Test 3 was successful!
All tests done.

**Comment by Maschell** [comment]
@piratesephiroth thanks, that's helpful. Can you verifiy that all test are passing with the [newest nightly](https://github.com/Maschell/WiiUPluginSystem/releases/tag/WiiUPluginLoader-alpha-nightly-a500538)?
@FunThomas76  Good to see no issues on 5.5.1

Someone reported that GBA VC games are not working. Can somebody confirm if virtual console games in general don't work with memory mapping enabled?

**If you see any crash, please send me the full log (+ some details where it crashed).**
It would be also awesome if you could re-run the step to trigger the step, but load the plugin loader normally this time (with **Plus**). This still logs some memory stuff, but doesn't map new memory (and hopefully don't crash). Both logs would be very helpful.

**Comment by piratesephiroth** [comment]
Both SNES VC and GBA VC work fine here.

All tests pass normally until after I visit the eshop link in the notifications.
Results seems to vary slightly depending on which notification I open.

Testing memory region 3. 0x88000000 - 0x8AB20000. Size 0x02B20000 (44160 KBytes).
+ Good  between 0x88000000 and 0x88856800 size: 8538 kB
- Error between 0x88856800 and 0x88860000 size: 38 kB
+ Good  between 0x88860000 and 0x8AB20000 size: 35584 kB                            



Testing memory region 3. 0x88000000 - 0x8AB20000. Size 0x02B20000 (44160 KBytes).
+ Good  between 0x88000000 and 0x888552AC size: 8532 kB
- Error between 0x888552AC and 0x88860000 size: 43 kB
+ Good  between 0x88860000 and 0x8AB20000 size: 35584 kB                          


                           
Testing memory region 3. 0x88000000 - 0x8AB20000. Size 0x02B20000 (44160 KBytes).
+ Good  between 0x88000000 and 0x88853BDC size: 8526 kB
- Error between 0x88853BDC and 0x88860000 size: 49 kB
+ Good  between 0x88860000 and 0x8AB20000 size: 35584 kB

**Comment by wicksand420** [comment]
The GBA VC's inject is what was crashing for me.

**Comment by Maschell** [comment]
@piratesephiroth  Thanks, Once again I adjusted the size of the chunk. [Now it should work?](https://github.com/Maschell/WiiUPluginSystem/releases/tag/WiiUPluginLoader-alpha-nightly-b4a07cf)

@wicksand420 That shouldn't make a difference if it's injected. Which base game are you using? That could be the problem.

**Comment by downloadpizza** [comment]
I can play Splatoon or Sm4sh modded (1Gig Modpack) with HIDtoVPAD Network Client and no problems

**Comment by piratesephiroth** [comment]
@Maschell, yep, no errors at all now.

**Comment by wicksand420** [comment]
@Maschell I'm not sure what the base was on the inject, I got it like 3 years ago, but I loaded a wii u game before the gba inject and got a crash, I'm not sure if that makes a difference, but I'm about to try a few more things with your latest nightly, so I'll try that again and post my results.
