### ISSUE TITLE
Splatoon Lag

### ISSUE THREAD

**Issue by downloadpizza** [wiiu-env/WiiUPluginSystem#18]
I have extreme Lag in Splatoon (around 14 Fps but it just slows down cause there is no Frameskip) as long as the example Modpack is loaded. When I put it out of the plugins folder the Lag is gone. Maybe put a option on start like the screenshot and swipswap Combination Setings.

**Comment by Maschell** [comment]
The example plugins is just an coding example, I should remove it from the nightly release.
A proper GUI where to choose the plugins that will be loaded is following

**Comment by Maschell** [comment]
I removed the plugins from the loader release, this should "solve" the problem. Having an option in the loader to enable / disable with hopefully follow soon
