### ISSUE TITLE
SD Caffine Suggestion: allow selection of multiple mods

### ISSUE THREAD

**Issue by mariomadproductions** [wiiu-env/WiiUPluginSystem#30]
Putting this here as you haven't enabled issues on your fork of SDCaffine and I don't think the original repo is being maintained anymore.

Suggestion:
The menu that appears when there are multiple mods in the title's sdcaffine folder should allow you to select more than one mod. File conflicts could be accounted for by giving some way to specify priorities, in the menu and/or via a config file or file/folder-naming scheme.

**Comment by UnasZole** [comment]
I like the suggestion.
Riivolution had the ability to combine several mod folders into a single configuration : I used that a lot for modding Brawl and it would be really cool if SDCafiine could do the same :-)

Also, @Maschell , could you enable the Issues tracking tab for the SDCafiine repo ?
It would be better than spamming your other repos with unrelated issues :-)
(And I have a few issues/questions with SDCafiine I'd like to check with you, as I've been toying with it these last few days).
