### ISSUE TITLE
MK8 freezes (black screen) when using latest wups plugin loader and wups-sdcafiine on 5.5.2 - Please help?

### ISSUE THREAD

**Issue by jack4455667788** [wiiu-env/WiiUPluginSystem#31]
Thank you so much for all your work!  WUPS is super great.

I have tried all the combinations (I think) of alpha/beta releases of both the wups-sdcaffiine plugin and the wiiu plugin loader app to no avail.

Whenever I load up sdcaffiine with MK8 (botw seems to work) I get a black screen and no further loading.

Can you help / any chance you have a 5.5.2 "version" laying around?

EDIT: SDCaffiine stable (non WUPS) loaded from the HBL works as expected.

**Comment by Ashel01** [comment]
The same happens to me
