### ISSUE TITLE
Create a wiki with information

### ISSUE THREAD

**Issue by Maschell** [wiiu-env/WiiUPluginSystem#5]
It would be really helpful to have a nice wiki with
- information for developers of plugins
- information for developers of the loader
- the end user on how to use it

**Comment by downloadpizza** [comment]
I could write something for the end user part, I think we should have a README.txt or a fancy readme html file in the Downloads.

**Comment by Gabgab2003** [comment]
There you go
[HOWTOUSE.txt](https://github.com/Maschell/WiiUPluginSystem/files/1886323/HOWTOUSE.txt)
