### ISSUE TITLE
Adding more hooks

### ISSUE THREAD

**Issue by Maschell** [wiiu-env/WiiUPluginSystem#9]
Idea: 
- Exit hook (__PPC_Exit)
- Hook for each Frame

**Comment by felixm456** [comment]
More hooks were added with commit https://github.com/Maschell/WiiUPluginSystem/commit/2aadfcf68e0202ecb413e01828ed3838251b7456

**Comment by Maschell** [comment]
Was added with commit https://github.com/Maschell/WiiUPluginSystem/commit/2aadfcf68e0202ecb413e01828ed3838251b7456
